FROM nginx:stable-alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY  nginx-conf.d /etc/nginx/conf.d

RUN rm /var/log/nginx/access.log && \
    rm /var/log/nginx/error.log  

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]